from pathlib import Path
from typing import Iterable, Optional, Tuple
from pathspec import PathSpec

def parse_cgcignore_lines(lines: Iterable[str]) -> list[str]:
    """Return valid ignore patterns from raw .cgcignore lines.

    Valid patterns are non-empty lines that do not start with '#'.
    """
    patterns: list[str] = []
    for raw_line in lines:
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        patterns.append(line)
    return patterns


def find_cgcignore(ignore_root: Path, explicit_path: Optional[str] = None) -> Optional[Path]:
    """Find a .cgcignore file, preferring an explicit path when provided."""
    if explicit_path:
        candidate = Path(explicit_path)
        if not candidate.is_absolute():
            candidate = (ignore_root / candidate).resolve()
        if candidate.exists():
            return candidate

    # Search parent folders only within the current git worktree. If the
    # indexed path is outside a git repo (e.g. /tmp test dirs), avoid crawling
    # up to filesystem-wide locations like /tmp/.cgcignore.
    git_root: Optional[Path] = None
    probe = ignore_root
    while True:
        if (probe / ".git").exists():
            git_root = probe
            break
        if probe.parent == probe:
            break
        probe = probe.parent

    curr = ignore_root
    while True:
        candidate = curr / ".cgcignore"
        if candidate.exists():
            return candidate

        if git_root is None:
            return None

        if curr == git_root:
            return None

        curr = curr.parent

def ensure_default_cgcignore(path: Path, default_patterns: list[str]) -> None:
    """Create a .cgcignore file with default patterns when it does not exist."""
    path.parent.mkdir(parents=True, exist_ok=True)
    content = "# Auto-generated by CodeGraphContext\n"
    content += "# Default ignore patterns for binary/media files\n"
    content += "# Add your own patterns below\n\n"
    content += "\n".join(default_patterns) + "\n"
    path.write_text(content, encoding="utf-8")


def read_cgcignore_patterns(path: Path, default_patterns: list[str]) -> list[str]:
    """Read .cgcignore patterns and merge them with defaults.

    Empty lines and comment lines are ignored.
    """
    if not path.exists():
        return list(default_patterns)

    user_patterns = parse_cgcignore_lines(path.read_text(encoding="utf-8").splitlines())
    return list(default_patterns) + user_patterns

def build_ignore_spec(
    ignore_root: Path,
    default_patterns: list[str],
    explicit_path: Optional[str] = None,
) -> Tuple[PathSpec, Optional[Path]]:
    """Build PathSpec using merged default + user .cgcignore patterns.

    Returns the compiled spec and the discovered/created .cgcignore path.
    """
    cgcignore_path = find_cgcignore(ignore_root, explicit_path)

    if cgcignore_path:
        all_patterns = read_cgcignore_patterns(cgcignore_path, default_patterns)
        return PathSpec.from_lines("gitwildmatch", all_patterns), cgcignore_path

    if explicit_path:
        target_path = Path(explicit_path)
        if not target_path.is_absolute():
            target_path = (ignore_root / target_path).resolve()
    else:
        target_path = ignore_root / ".cgcignore"
    ensure_default_cgcignore(target_path, default_patterns)
    return PathSpec.from_lines("gitwildmatch", default_patterns), target_path
